### ISSUE TITLE
make deb-package does not work

### ISSUE THREAD

**Issue by falfaro** [eandriol/kvm-deploy#1]
Instructions for "make deb-package" don't work:

$ git clone https://github.com/eandriol/kvm-deploy.git
$ cd kvm-deploy
$ make deb-package
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
Makefile:102: recipe for target 'deb-package' failed
make: *** [deb-package] Error 29
$ dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning:     debian/changelog(l1): version '%VERSION%' is invalid: version number does not start with digit
LINE: kvm-deploy (%VERSION%) stable; urgency=low
dpkg-buildpackage: warning:     debian/changelog(l5): badly formatted trailer line
LINE:  -- Elwin Andriol <e.andriol@gmail.com>  %TIMESTAMP%
dpkg-buildpackage: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
dpkg-buildpackage: source package kvm-deploy
dpkg-buildpackage: source version %%VERSION%%
dpkg-buildpackage: error: version number does not start with digit

**Comment by eandriol** [comment]
I just tried it on one of my machines and it still works as it should. In your case, it appears that the value substitution in the Debian changelog template has failed. My best guess is that you do not have 'sed' installed on your system (apt-get install sed). Line 32-40 list all required system tools. I am not sure why make did not fail or complain at an earlier stage. Another potential problem could be the type of shell you use. When I try to reproduce your problem, using Debian's default bash as my shell, I get the following output.

root@dev:~/test# git clone https://github.com/eandriol/kvm-deploy.git
Cloning into 'kvm-deploy'...
remote: Counting objects: 116, done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 116 (delta 29), reused 116 (delta 29), pack-reused 0
Receiving objects: 100% (116/116), 455.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (29/29), done.
Checking connectivity... done.
root@dev:~/test# cd kvm-deploy
root@dev:~/test/kvm-deploy# make deb-package
package location: /root/test/kvm-deploy/build/kvm-deploy_1.1_all.deb

**Comment by falfaro** [comment]
I am using Ubuntu 16.04 and sed is installed on my system for sure. I'm using "bash". For me:

y# make deb-package
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
Makefile:102: recipe for target 'deb-package' failed
make: *** [deb-package] Error 29

And:

# dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: warning:     debian/changelog(l1): version '%VERSION%' is invalid: version number does not start with digit
LINE: kvm-deploy (%VERSION%) stable; urgency=low
dpkg-buildpackage: warning:     debian/changelog(l5): badly formatted trailer line
LINE:  -- Elwin Andriol <e.andriol@gmail.com>  %TIMESTAMP%
dpkg-buildpackage: warning:     debian/changelog(l6): found end of file where expected more change data or trailer
dpkg-buildpackage: source package kvm-deploy
dpkg-buildpackage: source version %%VERSION%%
dpkg-buildpackage: error: version number does not start with digit

So I'm not sure what am I missing.

**Comment by eandriol** [comment]
If you did not clean up the output you gave me, i.e. it was everything produced with the 'make dep-package' command, then I am really puzzled as to what could have produced your problem.

Running 'dpkg-buildpackage' from the project's root directory is for sure not going to work, for you would run it against the template 'debian' directory instead from the proper sub directory within the build directory.

The 'deb-package' target should substitute template markers (e.g. %%VERSION%% and %%TIMESTAMP%%) within the changelog template file with meaningful values. Sed is used for that purpose. It is a mystery to me, how apparently these instructions are executed on your system but did not update the changelog file in your build directory. It is as if sed just didn't dot its work at all.

The first line of the file 'build/kvm-deploy-1.1/debian/changelog' should not start with 'kvm-deploy (%%VERSION%%)', but instead start with 'kvm-deploy (1.1)'.
